pipelines = [
    ["A", [{"input": {"process": "__init__", "lane": 1},
            "output": {"process": "A", "lane": 1}}]],
    ["A B", [{"input": {"process": "__init__", "lane": 1},
              "output": {"process": "A", "lane": 1}},
             {"input": {"process": "A", "lane": 1},
              "output": {"process": "B", "lane": 1}}]],
    ["A B (C | D)", [{"input": {"process": "__init__", "lane": 1},
                      "output": {"process": "A", "lane": 1}},
                     {"input": {"process": "A", "lane": 1},
                      "output": {"process": "B", "lane": 1}},
                     {"input": {"process": "B", "lane": 1},
                      "output": {"process": "C", "lane": 2}},
                     {"input": {"process": "B", "lane": 1},
                      "output": {"process": "D", "lane": 3}}]],
    ["A B (C | D E F)", [{"input": {"process": "__init__", "lane": 1},
                          "output": {"process": "A", "lane": 1}},
                         {"input": {"process": "A", "lane": 1},
                          "output": {"process": "B", "lane": 1}},
                         {"input": {"process": "B", "lane": 1},
                          "output": {"process": "C", "lane": 2}},
                         {"input": {"process": "B", "lane": 1},
                          "output": {"process": "D", "lane": 3}},
                         {"input": {"process": "D", "lane": 3},
                          "output": {"process": "E", "lane": 3}},
                         {"input": {"process": "E", "lane": 3},
                          "output": {"process": "F", "lane": 3}}]],
    ["(A | B | C)", [{"input": {"process": "__init__", "lane": 0},
                      "output": {"process": "A", "lane": 1}},
                     {"input": {"process": "__init__", "lane": 0},
                      "output": {"process": "B", "lane": 2}},
                     {"input": {"process": "__init__", "lane": 0},
                      "output": {"process": "C", "lane": 3}}]],
    ["(A | B | C E (F | G))", [{"input": {"process": "__init__", "lane": 0},
                                "output": {"process": "A", "lane": 1}},
                               {"input": {"process": "__init__", "lane": 0},
                                "output": {"process": "B", "lane": 2}},
                               {"input": {"process": "__init__", "lane": 0},
                                "output": {"process": "C", "lane": 3}},
                               {"input": {"process": "C", "lane": 3},
                                "output": {"process": "E", "lane": 3}},
                               {"input": {"process": "E", "lane": 3},
                                "output": {"process": "F", "lane": 4}},
                               {"input": {"process": "E", "lane": 3},
                                "output": {"process": "G", "lane": 5}}]],
    ["(A (Z | X)| B | C E (F | G))",
                    [{"input": {"process": "__init__", "lane": 0},
                      "output": {"process": "A", "lane": 1}},
                     {"input": {"process": "__init__", "lane": 0},
                      "output": {"process": "B", "lane": 2}},
                     {"input": {"process": "__init__", "lane": 0},
                      "output": {"process": "C", "lane": 3}},
                     {"input": {"process": "C", "lane": 3},
                      "output": {"process": "E", "lane": 3}},
                     {"input": {"process": "A", "lane": 1},
                      "output": {"process": "Z", "lane": 4}},
                     {"input": {"process": "A", "lane": 1},
                      "output": {"process": "X", "lane": 5}},
                     {"input": {"process": "E", "lane": 3},
                      "output": {"process": "F", "lane": 6}},
                     {"input": {"process": "E", "lane": 3},
                      "output": {"process": "G", "lane": 7}}]],
    ["(A (Z | X)| B(Y|H A) | C E (F | G))",
     [{"input": {"process": "__init__", "lane": 0},
       "output": {"process": "A", "lane": 1}},
      {"input": {"process": "__init__", "lane": 0},
       "output": {"process": "B", "lane": 2}},
      {"input": {"process": "__init__", "lane": 0},
       "output": {"process": "C", "lane": 3}},
      {"input": {"process": "C", "lane": 3},
       "output": {"process": "E", "lane": 3}},
      {"input": {"process": "A", "lane": 1},
       "output": {"process": "Z", "lane": 4}},
      {"input": {"process": "A", "lane": 1},
       "output": {"process": "X", "lane": 5}},
      {"input": {"process": "B", "lane": 2},
       "output": {"process": "Y", "lane": 6}},
      {"input": {"process": "B", "lane": 2},
       "output": {"process": "H", "lane": 7}},
      {"input": {"process": "H", "lane": 7},
       "output": {"process": "A", "lane": 7}},
      {"input": {"process": "E", "lane": 3},
       "output": {"process": "F", "lane": 8}},
      {"input": {"process": "E", "lane": 3},
       "output": {"process": "G", "lane": 9}}]]
]
