import os
import flowcraft.templates.pATLAS_consensus_json as pATLAS_consensus_json


def test_generate_file(tmpdir):
    """
    This function tests if the files generated by this template script are
    created
    """

    # create a temporary file mash screen txt file
    mash_file = tmpdir.join("mash_file.txt")
    depth_file = tmpdir.join("test_depth_file.txt")
    mash_file.write('{"ACC1": ["0.9", "1"]}')
    depth_file.write('{"ACC1": 0.9}')

    list_of_files = [str(mash_file), str(depth_file)]

    pATLAS_consensus_json.main(list_of_files)

    assert_message = []
    # conditions to check that files are generated
    if not os.path.isfile("consensus_file.json".format(
            str(mash_file).split(".")[0])):
        assert_message.append("consensus_file.json not created")
    if not os.path.isfile(".report.json"):
        assert_message.append(".report.json file was not created")

    # remove the .report.json file
    os.remove(".report.json")
    os.remove("consensus_file.json")

    assert not assert_message, "errors occurred:\n{}".format(
        "\n".join(assert_message)
    )
