import os
import json
import flowcraft.templates.mapping2json as mapping2json

depth_dict_coverage = {
    "ACC1": {
        "1": 20,
        "2": 30,
        "3": 50,
        "4": 40,
        "5": 30,
        "6": 20,
        "7": 20,
        "8": 40,
        "9": 30,
        "10": 20
    },
    "ACC2": {
        "1": 20,
        "2": 30,
        "3": 50,
        "4": 40,
        "7": 20,
        "8": 40,
        "9": 30,
        "10": 20
    }
}

#
plasmid_length = {
    "ACC1": "10",
    "ACC2": "10"
}


def test_depth_file_reader(tmpdir):
    """
    test the output of depth_file_reader_function to be a given dict
    """

    # create a temporary file to make a dict from
    file = tmpdir.join("test_depth_file.txt")
    file.write("seq1\t1\t30")

    # execute the function to get the dict
    result_dict = mapping2json.depth_file_reader(open(str(file)))

    assert result_dict == {"seq1": {"1": 30}}


def test_generate_jsons():
    """
    Test if the returns from this function are the expected results
    """
    perc_bases_cov, dict_cov = mapping2json.generate_jsons(depth_dict_coverage,
                                                           plasmid_length, 0.9)

    # asserts if all the returned values are the expected ones
    assert (perc_bases_cov, dict_cov) == (
        {"ACC1": 1.0},
        {"ACC1": {
            "length": 10,
            "interval": 1,
            "values": [20, 30, 50, 40, 30, 20, 20, 40, 30, 20]
        }}
    )


def test_generate_file(tmpdir):
    """
    This function tests if the files are generated by the main function.
    .report.json and the file to import in pATLAS.
    """

    # create a temporary file depth txt file
    depth_file = tmpdir.join("test_depth_file.txt")
    depth_file.write("seq1\t1\t30")

    # creates a temporary file with the json_dict
    json_dict = tmpdir.join("test_json_dict.json")
    json_dict.write('{"seq1": 2000}')

    # executes the function to be tested
    mapping2json.main(str(depth_file), str(json_dict), "0", "test")

    assert_message = []
    # conditions to check that files are generated
    if not os.path.isfile("{}_mapping.json".format(str(depth_file))):
        assert_message.append("_mapping.json not created")
    if not os.path.isfile(".report.json"):
        assert_message.append(".report.json file was not created")

    # remove the .report.json file
    os.remove(".report.json")

    assert not assert_message, "errors occurred:\n{}".format(
        "\n".join(assert_message)
    )


def test_generated_dict(tmpdir):
    """
    This function tests if the files generated by this template script are
    created
    """

    # create a temporary file depth txt file
    depth_file = tmpdir.join("test_depth_file.txt")
    depth_file.write("ACC1\t1\t30")

    # creates a temporary file with the json_dict
    json_dict = tmpdir.join("test_json_dict.json")
    json_dict.write('{"ACC1": 2000}')

    expected_dict = {"ACC1": 0.0}

    # executes the function to be tested
    mapping2json.main(str(depth_file), str(json_dict), "0", "test")

    result_dict = json.load(open("{}_mapping.json".format(str(depth_file))))

    assert_message = []

    # checks if result_dict is indeed a dictionary
    if not isinstance(result_dict, dict):
        assert_message.append("Contents of the generated file must be a "
                              "dictionary.")

    if not result_dict == expected_dict:
        assert_message.append("The expected dictionary must be equal to the "
                              "one present in the generated file.\n"
                              "Expected: {}\n"
                              "Result: {}". format(
            json.dumps(expected_dict),
            json.dumps(result_dict)
        ))

    # remove the .report.json file
    os.remove(".report.json")

    assert not assert_message, "Errors occurred:\n{}".format(
        "\n".join(assert_message)
    )
