import os
import flowcraft.templates.mashdist2json as mashdist2json


def test_generate_file(tmpdir):
    """
    This function tests if the files generated by this template script are
    created
    """

    # create a temporary file mash screen txt file
    mash_file = tmpdir.join("test_depth_file.txt")
    mash_file.write("NC_ACC_1_seq\tseq1\t100\t900/1000")

    mashdist2json.main(str(mash_file), "0.5", "test", "assembly_file")

    assert_message = []
    # conditions to check that files are generated
    if not os.path.isfile("{}.json".format(
            str(mash_file).split(".")[0])):
        assert_message.append("mash dist json not created")
    if not os.path.isfile(".report.json"):
        assert_message.append(".report.json file was not created")

    # remove the .report.json file
    os.remove(".report.json")

    assert not assert_message, "errors occurred:\n{}".format(
        "\n".join(assert_message)
    )
