#!/usr/bin/env python3

import os
import json
import dendropy

from flowcraft_utils.flowcraft_base import get_logger, MainWrapper



"""
Purpose
-------

This module is intended to process the newick generated by
 a proces to generate a report. The newick tree will be 
 rooted (midpoint). 
 
 
Expected input
--------------

The following variables are expected whether using NextFlow or the
:py:func:`main` executor.

- ``newick``: phylogenetic tree in newick format.

Generated output
----------------
- ``.report.jason``: Data structure for the report

Code documentation
------------------

"""

__version__ = "1.0.2"
__build__ = "28.12.2018"
__template__ = "raxml-nf"

logger = get_logger(__file__)


if __file__.endswith(".command.sh"):
    NEWICK = '$newick'
    LABELS = '$label'
    logger.debug("Running {} with parameters:".format(
        os.path.basename(__file__)))
    logger.debug("NEWICK: {}".format(NEWICK))
    logger.debug("LABELS: {}".format(LABELS))



@MainWrapper
def main(newick, labels):
    """Main executor of the process_newick template.

    Parameters
    ----------
    newick : str
        path to the newick file.

    """

    logger.info("Starting newick file processing")

    #load tree and midpoint root
    tree = dendropy.Tree.get(file=open(newick, 'r'), schema="newick")
    tree.reroot_at_midpoint()

    to_write_trees = tree.as_string("newick").strip().replace("[&R] ", '').replace(' ', '_').replace("'", "")

    #add labels to replace taxon names in phylocanvas
    labels_dict = {}

    if labels == 'true':

        original_labels = tree.update_taxon_namespace()

        for item in original_labels:

            original_name = str(item).strip().replace("[&R] ", '').replace(' ', '_').replace("'", "")

            # if it's a reference sequence
            if '|' in original_name:
                new_name = original_name.split('|')[0]
            else:
                # in case it's a reversed complement sequence or a genebank reference
                new_name = original_name.replace("_R_", "").replace("gb_", "gb:").split('_')[0]

            labels_dict[original_name] = new_name

    # write report in json format
    with open(".report.json", "w") as json_report:
        json_dic = {
            "treeData": [{
                "trees": [
                    to_write_trees
                ],
                "labels":[
                    labels_dict
                ]
            }],
        }

        json_report.write(json.dumps(json_dic, separators=(",", ":")))

    with open(".status", "w") as status_fh:
        status_fh.write("pass")


if __name__ == '__main__':
    main(NEWICK, LABELS)

